# Built with Jekyll 3.2.0

# Setup
title:               "DUB."
tagline:             "doblatge unida de barcelona"
description:         "dub. és una associació professional de doblatge de Barcelona"
url:                 "https://dubbcn.org"
baseurl:             ""

# About/contact
author:
  name:              Masumi Mutsuda
  url:               https://twitter.com/dubbcn
  email:             hola@dubbcn.org

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: blue

# Permalinks
permalink: pretty
permalink: /:title/
permalink: /blog/:year/:month/:day/:title/

# Set encoding to UTF-8
encoding: utf-8


# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


include: [_redirects]

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
